#ifndef PACKET_FORMAT_H
#define PACKET_FORMAT_H

#include <Arduino.h>
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

// Shared compact telemetry packet protocol used by BOTH transmitter and
// receiver (must agree exactly).
//
// GPS telemetry packet (comma separated, no whitespace):
//   GPS,<seq>,<valid>,<lat>,<lng>,<date>,<time>,<sats>,<hdop>
//   e.g. GPS,105,1,23.780573,90.407113,2026-08-10,06:35:20,11,0.92
//
//   <seq>    uint32 sequence (increments each transmitted packet)
//   <valid>  1 if GPS has a fix, else 0 (NO FIX)
//   <lat>    latitude  signed decimal degrees, 6 decimals
//   <lng>    longitude signed decimal degrees, 6 decimals
//   <date>   UTC date "YYYY-MM-DD" (or 0000-00-00 when unavailable)
//   <time>   UTC time "HH:MM:SS" (or 00:00:00 when unavailable)
//   <sats>   number of satellites (0 when unavailable)
//   <hdop>   HDOP as float (0.00 when unavailable)
//
// STM32 sensor telemetry packet (comma separated, no whitespace) - 25 tokens:
//   STM,<tseq>,<sseq>,
//       <ntc1t>,<ntc2t>,<ntc3t>,<ntc4t>,<ntc5t>,<ntc6t>,<ntc7t>,<ntc8t>,
//       <ntc1raw>,<ntc2raw>,<ntc3raw>,<ntc4raw>,<ntc5raw>,<ntc6raw>,<ntc7raw>,<ntc8raw>,
//       <gy1v>,<gy1t>,<gy1h>,<gy2v>,<gy2t>,<gy2h>
//   e.g. STM,101,45,265,261,-152,-253,-292,-316,-368,-466,2205,2180,1900,1750,
//        1600,1500,1400,1200,1,4215,5732,1,3188,6021
//
//   <tseq>   uint32 LoRa TRANSPORT sequence (SAME space as GPS; generated by
//            the ESP32, NOT by the STM32)
//   <sseq>   uint32 STM32 SAMPLE sequence (generated by the STM32)
//   <ntcNt>  NTC N temperature in 0.1 C units (x10); -9990 = invalid NTC
//   <ntcNraw>NTC N raw 12-bit ADC count (0..4095)
//   <gyNv>   GY-21 #N valid flag (1 = valid, 0 = invalid)
//   <gyNt>   GY-21 #N temperature in 0.01 C units (x100)
//   <gyNh>   GY-21 #N humidity in 0.01 % units (x100)
//            -99900 = invalid GY-21 measurement
//
// ACK packet (receiver -> transmitter):
//   ACK,<seq>,<rxRssi>,<rxSnr>,<rxQuality>
//   e.g. ACK,105,-72,8.25,91
//   <seq>       ACKed telemetry TRANSPORT sequence number (GPS or STM)
//   <rxRssi>    telemetry packet RSSI measured by receiver (dBm)
//   <rxSnr>     telemetry packet SNR measured by receiver (dB)
//   <rxQuality> receiver-computed signal quality (0-100 %)

#define PTYPE_GPS "GPS"
#define PTYPE_STM "STM"
#define PTYPE_ACK "ACK"

// Maximum serialized packet length including NUL terminator. The 25-token STM
// packet reaches ~112 chars with the example values and ~145 chars in the
// worst case (large sequences / invalid sentinels), so 160 leaves headroom.
#define PACKET_BUF_SIZE 160

#define GPS_DATE_LEN 11   // "YYYY-MM-DD" + NUL
#define GPS_TIME_LEN 9    // "HH:MM:SS" + NUL

#define GPS_DATE_UNKNOWN "0000-00-00"
#define GPS_TIME_UNKNOWN "00:00:00"

// STM32 field sentinels / validation ranges (shared by TX UART parse + RX
// LoRa parse so both ends validate identically).
#define STM_NTC_TEMP_INVALID  (-9990)   // NTC temperature x10 sentinel
#define STM_NTC_TEMP_MIN      (-5000)   // x10 units = -500.0 C (generous bound)
#define STM_NTC_TEMP_MAX      (15000)   // x10 units = +1500.0 C (generous bound)
#define STM_NTC_RAW_MAX       (4095)    // 12-bit ADC
#define STM_GY_INVALID        (-99900)  // GY-21 scaled temp/humidity sentinel
#define STM_GY_TEMP_MIN       (-5000)   // x100 units = -50.0 C (generous bound)
#define STM_GY_TEMP_MAX       (15000)   // x100 units = +150.0 C (generous bound)
#define STM_GY_HUM_MAX        (10000)   // x100 units = 100.00 %

struct GpsData {
    uint32_t sequence;
    bool     valid;      // true == GPS has a fix
    double   latitude;
    double   longitude;
    char     date[GPS_DATE_LEN];
    char     time[GPS_TIME_LEN];
    uint8_t  satellites;
    float    hdop;
};

struct StmData {
    uint32_t transportSeq;      // LoRa TRANSPORT sequence (shared with GPS)
    uint32_t sampleSequence;    // STM32 SAMPLE sequence (from the STM32)
    int16_t  ntcTempX10[8];     // NTC 1..8 temp, 0.1 C units; STM_NTC_TEMP_INVALID = invalid
    uint16_t ntcRaw[8];         // NTC 1..8 raw 12-bit ADC (0..4095)
    bool     gy1Valid;          // GY-21 #1 measurement valid
    int32_t  gy1TempX100;       // GY-21 #1 temp, 0.01 C units; STM_GY_INVALID = invalid
    int32_t  gy1HumX100;        // GY-21 #1 humidity, 0.01 % units; STM_GY_INVALID = invalid
    bool     gy2Valid;          // GY-21 #2 measurement valid
    int32_t  gy2TempX100;       // GY-21 #2 temp, 0.01 C units; STM_GY_INVALID = invalid
    int32_t  gy2HumX100;        // GY-21 #2 humidity, 0.01 % units; STM_GY_INVALID = invalid
};

struct AckData {
    uint32_t sequence;
    int16_t  rxRssi;     // telemetry RSSI measured by receiver (dBm)
    float    rxSnr;      // telemetry SNR measured by receiver (dB)
    uint8_t  rxQuality;  // receiver-computed quality (0-100 %)
};

size_t buildGpsPacket(char *buf, size_t bufSize, const GpsData &gps);
bool parseGpsPacket(const char *buf, GpsData &gps);
size_t buildStmPacket(char *buf, size_t bufSize, const StmData &stm);
bool parseStmPacket(const char *buf, StmData &stm);
size_t buildAckPacket(char *buf, size_t bufSize, const AckData &ack);
bool parseAckPacket(const char *buf, AckData &ack);

#endif // PACKET_FORMAT_H
