; Receiver ESP32 (LoRa RX) -> COM10
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM10
monitor_port = COM10
lib_deps =
    sandeepmistry/LoRa
build_flags =
    -DCORE_DEBUG_LEVEL=0
src_filter = +<*> -<main_backup.cpp>
