; Transmitter ESP32 (LoRa TX + GPS) -> COM4
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
lib_deps =
    sandeepmistry/LoRa
    mikalhart/TinyGPSPlus
build_flags =
    -DCORE_DEBUG_LEVEL=0
