"""Embedded parity runner helpers.

This module compiles the C99 model against the golden vectors and asserts
that the runtime probability distributions match the Python pipeline outputs
to within tolerance. It produces ``evidence/embedded/parity_report.json`` and
``evidence/embedded/PARITY_REPORT.md`` summarizing the run.

Two hard gates are enforced:

1. **No uniform-probability stub.** A regression in the model exporter that
   re-introduces the placeholder ``1.0f / N`` distribution fails parity.
2. **C probabilities match Python probabilities** within ``1e-4`` maximum
   absolute error, and the predicted class index agrees for every vector.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = ROOT / "evidence" / "embedded"
GOLDEN_VECTORS_PATH = ROOT / "embedded" / "golden_vectors" / "golden_vectors.json"
GENERATED_DIR = ROOT / "embedded" / "generated"
TESTS_DIR = ROOT / "embedded" / "tests"

PROBABILITY_TOLERANCE = 1e-4


def _expected_probabilities_per_vector() -> tuple[list[list[float]], list[str]]:
    """Return aligned (Python pipeline) probability rows per golden vector.

    The C runtime emits class probabilities in the order ``sklearn.classes_``
    declared at export time. The Python pipeline produces probabilities in
    the same underlying class order; we look up the row order from the
    golden-vector JSON (which is generated by the same runtime) and re-derive
    each row in Python for the ground-truth comparison.
    """

    import joblib
    import numpy as np
    import yaml

    config = yaml.safe_load(
        (ROOT / "config" / "embedded_export.yaml").read_text(encoding="utf-8")
    )
    runtime_root = ROOT / config["selected_model_path"]
    # ``selected_model_path`` may be a directory containing latest_selected.json
    # or the path to a specific model artifact.
    latest = runtime_root / "latest_selected.json"
    if latest.exists():
        latest_info = json.loads(latest.read_text(encoding="utf-8"))
        artifact = (ROOT / latest_info["artifact_dir"]).resolve()
    else:
        artifact = runtime_root
    pipeline = joblib.load(artifact / "pipeline.joblib")
    classes = [str(c) for c in pipeline.classes_]
    raw = json.loads(GOLDEN_VECTORS_PATH.read_text(encoding="utf-8"))
    expected: list[list[float]] = []
    for vector in raw:
        features = vector["raw_feature_values"]
        order = list(features.keys())
        row = np.array([[float(features[k]) for k in order]], dtype=np.float64)
        proba = pipeline.predict_proba(row)[0]
        expected.append([float(p) for p in proba])
    return expected, classes


def run_parity() -> dict[str, object]:
    """Compile and run C parity harness when a compiler is available."""

    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    compiler = shutil.which("gcc") or shutil.which("clang") or shutil.which("cl")
    raw = json.loads(GOLDEN_VECTORS_PATH.read_text(encoding="utf-8"))
    vector_count = len(raw)
    report: dict[str, Any] = {
        "tested_vector_count": vector_count,
        "compiler": compiler or "unavailable",
        "compiler_flags": (
            "-std=c99" if compiler and compiler.endswith(("gcc", "gcc.exe")) else ""
        ),
        "preprocessing_max_absolute_error": None,
        "probability_max_absolute_error": None,
        "class_mismatch_count": None,
        "policy_mismatch_count": 0,
        "uniform_stub_count": None,
        "status": "blocked_no_compiler",
        "notes": "",
    }
    if compiler is None:
        report["notes"] = "No C compiler found. Install GCC or clang."
    else:
        exe = EVIDENCE_DIR / "parity_runner.exe"
        command = [
            compiler,
            "-std=c99",
            "-I",
            str(GENERATED_DIR),
            "-I",
            str(ROOT / "embedded" / "golden_vectors"),
            str(TESTS_DIR / "parity_runner.c"),
            str(GENERATED_DIR / "thermal_nexus_model.c"),
            "-o",
            str(exe),
            "-lm",
        ]
        try:
            result = subprocess.run(
                command, capture_output=True, text=True, check=False
            )
        except FileNotFoundError as exc:
            report["status"] = "failed"
            report["notes"] = f"compiler invocation failed: {exc}"
            _write_reports(report)
            return report
        if result.returncode != 0:
            report["status"] = "failed_compile"
            report["notes"] = (result.stdout + result.stderr).strip()
            _write_reports(report)
            return report
        run_result = subprocess.run(
            [str(exe)], capture_output=True, text=True, check=False
        )
        report["compile_stdout"] = result.stdout
        report["compile_stderr"] = result.stderr
        report["run_stdout"] = run_result.stdout
        report["run_stderr"] = run_result.stderr
        summary = _parse_run(run_result.stdout, vector_count)
        report.update(summary)
        expected, classes = _expected_probabilities_per_vector()
        diffs: list[float] = []
        class_mismatches = 0
        for i, (emitted, expect) in enumerate(zip(summary["vectors"], expected)):
            for k, (a, b) in enumerate(zip(emitted["probs"], expect)):
                diffs.append(abs(a - b))
            if emitted["class"] != max(range(len(expect)), key=lambda j: expect[j]):
                class_mismatches += 1
        report["probability_max_absolute_error"] = max(diffs) if diffs else 0.0
        report["class_mismatch_count"] = class_mismatches
        report["policy_mismatch_count"] = class_mismatches
        report["class_order"] = classes
        report["expected_probabilities"] = expected
        report["emitted_probabilities"] = summary["vectors"]
        gate_pass = (
            summary["uniform_stub_count"] == 0
            and report["probability_max_absolute_error"] <= PROBABILITY_TOLERANCE
            and class_mismatches == 0
            and run_result.returncode == 0
        )
        report["status"] = "pass" if gate_pass else "failed"
        report["notes"] = (
            f"Tested {vector_count} vectors with {compiler}. "
            f"Max probability error: {report['probability_max_absolute_error']:.2e}. "
            f"Class mismatches: {class_mismatches}. "
            f"Uniform-stub vectors: {summary['uniform_stub_count']}."
        )
    _write_reports(report)
    return report


def _parse_run(stdout: str, vector_count: int) -> dict[str, Any]:
    vectors: list[dict[str, Any]] = []
    uniform_stub_count = 0
    class_mismatches = 0
    for line in stdout.splitlines():
        if line.startswith("vector="):
            parts = line.split()
            index = int(parts[0].split("=")[1])
            predicted = int(parts[1].split("=")[1])
            probs = [float(x) for x in parts[2].split("=")[1].split(";")]
            vectors.append({"index": index, "class": predicted, "probs": probs})
            expected_uniform = 1.0 / max(len(probs), 1)
            if all(abs(p - expected_uniform) < 1e-3 for p in probs):
                uniform_stub_count += 1
        elif line.startswith("summary"):
            tokens = line.split()
            for token in tokens:
                if token.startswith("class_mismatches="):
                    class_mismatches = int(token.split("=")[1])
                if token.startswith("uniform_stub="):
                    uniform_stub_count = int(token.split("=")[1])
    return {
        "vectors": vectors,
        "uniform_stub_count": uniform_stub_count,
        "class_mismatches": class_mismatches,
    }


def _write_reports(report: dict[str, Any]) -> None:
    (EVIDENCE_DIR / "parity_report.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8"
    )
    (EVIDENCE_DIR / "PARITY_REPORT.md").write_text(
        _markdown(report), encoding="utf-8"
    )


def _markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Embedded Parity Report",
        "",
        f"Status: `{report['status']}`",
        f"Compiler: `{report['compiler']}`",
        f"Tested vectors: {report['tested_vector_count']}",
        "",
    ]
    if report["probability_max_absolute_error"] is not None:
        lines.append(
            f"- Max probability absolute error: "
            f"`{report['probability_max_absolute_error']:.2e}` "
            f"(tolerance {PROBABILITY_TOLERANCE:.0e})"
        )
    if report["class_mismatch_count"] is not None:
        lines.append(f"- Class mismatches: `{report['class_mismatch_count']}`")
    if report["uniform_stub_count"] is not None:
        lines.append(f"- Uniform-stub vectors: `{report['uniform_stub_count']}`")
    if report["preprocessing_max_absolute_error"] is not None:
        lines.append(
            f"- Preprocessing max absolute error: "
            f"`{report['preprocessing_max_absolute_error']:.2e}`"
        )
    lines.append("")
    lines.append(report.get("notes", ""))
    return "\n".join(lines)


if __name__ == "__main__":
    print(json.dumps(run_parity(), indent=2))