"""KPI catalog for offline Thermal Nexus reports."""

from __future__ import annotations

from dataclasses import dataclass

ESTIMATED_SOFTWARE_VALUE = "ESTIMATED_SOFTWARE_VALUE"
SIMULATED_SOFTWARE_VALUE = "SIMULATED_SOFTWARE_VALUE"


@dataclass(frozen=True)
class KpiDefinition:
    """One explicit KPI definition."""

    name: str
    description: str
    formula: str
    unit: str
    required_source_fields: list[str]
    applicable_modes: list[str]
    assumptions: str
    limitations: str
    value_type: str


KPI_DEFINITIONS = {
    "total_sensor_samples": KpiDefinition(
        "total_sensor_samples",
        "Count of node decision rows.",
        "count(node_decisions)",
        "count",
        ["node_decisions.id"],
        ["fixed", "rule_based", "ml"],
        "One decision row represents one synthetic sample.",
        "Software simulation only.",
        SIMULATED_SOFTWARE_VALUE,
    ),
    "total_transmissions": KpiDefinition(
        "total_transmissions",
        "Count of requested transmissions.",
        "sum(transmission_requested)",
        "count",
        ["node_decisions.transmission_requested"],
        ["fixed", "rule_based", "ml"],
        "Requested packets are generated by the virtual node.",
        "Not measured RF traffic.",
        SIMULATED_SOFTWARE_VALUE,
    ),
    "packet_delivery_ratio": KpiDefinition(
        "packet_delivery_ratio",
        "Delivered packets divided by requested transmissions.",
        "accepted reader records / requested transmissions",
        "ratio",
        ["reader_records.accepted", "node_decisions.transmission_requested"],
        ["fixed", "rule_based", "ml"],
        "Reader accepted records represent delivered valid packets.",
        "Software radio model only.",
        SIMULATED_SOFTWARE_VALUE,
    ),
    "packet_loss_rate": KpiDefinition(
        "packet_loss_rate",
        "Dropped radio events divided by sent packets.",
        "dropped events / transmissions",
        "ratio",
        ["radio_events.event_type", "node_decisions.transmission_requested"],
        ["fixed", "rule_based", "ml"],
        "Drop events are simulator events.",
        "No physical range claim.",
        SIMULATED_SOFTWARE_VALUE,
    ),
    "retry_count": KpiDefinition(
        "retry_count",
        "Total radio retry count.",
        "sum(radio_events.retry_number)",
        "count",
        ["radio_events.retry_number"],
        ["fixed", "rule_based", "ml"],
        "Retries are simulated.",
        "No XBee reliability claim.",
        SIMULATED_SOFTWARE_VALUE,
    ),
    "mean_warning_lead_time": KpiDefinition(
        "mean_warning_lead_time",
        "First excursion crossing time minus first risk warning time.",
        "first excursion timestamp - first EXCURSION_RISK state timestamp",
        "seconds",
        ["node_decisions.applied_state", "node_decisions.measured_temperature"],
        ["fixed", "rule_based", "ml"],
        "Temperature limits are synthetic cold-chain limits.",
        "Single-run result has no statistical significance.",
        SIMULATED_SOFTWARE_VALUE,
    ),
    "estimated_total_energy": KpiDefinition(
        "estimated_total_energy",
        "Estimated total software energy units.",
        "sensing estimate + inference estimate + radio estimate",
        "estimated unit",
        ["node_decisions"],
        ["fixed", "rule_based", "ml"],
        "Uses configured software constants.",
        "Not measured Wh or STM32 consumption.",
        ESTIMATED_SOFTWARE_VALUE,
    ),
}
